[project]
name = "dcov"
version = "0.1.1"
description = ""
authors = [
  {email = "EgodPrime@gmail.com"},
  {name = "Senyi Li"}
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "fire",
]

[project.optional-dependencies]
dev=[
  "black", 
  "pytest-cov",
  "ruff",
  "pytest",
  "PyYAML"
]

[tool.ruff]
line-length = 88
fix = true

[tool.ruff.lint]
select = ["F401", "F403"]

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=html:htmlcov --cov-report=term-missing -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[project.scripts]
dcov_python = "dcov.cmd.dcov_python:main"