[project]
name = "dcov"
version = "0.1.1"
description = ""
authors = [
  {email = "EgodPrime@gmail.com"},
  {name = "Senyi Li"}
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "fire",
]

[project.optional-dependencies]
dev=[
  "black", 
  "isort",
  "pytest"
]

[tool.black]
line-length = 102
target-version = ["py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "dcov.python._core"
python-packages = ["dcov"]
python-source = "src"

[project.scripts]
dcov_python = "dcov.cmd.dcov_python:main"