def get_bitmap_size() -> int: ...
def open_bitmap_py() -> None: ...
def clear_bitmap_py() -> None: ...
def close_bitmap_py() -> None: ...
def count_bitmap_py() -> int: ...
def set_bit_py(index: int) -> None: ...
def add_edge_py(src: int, dst: int) -> None: ...
def get_bytemap_size() -> int: ...
def get_bitmap_size() -> int: ...
