class BitmapManager:
    def __init__(self, shm_key: int) -> None: ...
    def clear_bitmap(self) -> None: ...
    def close_bitmap(self) -> None: ...
    def count_bitmap(self) -> int: ...
    def count_bitmap_s(self) -> int: ...
    def set_bit(self, index: int) -> None: ...
    def add_edge(self, index: int) -> None: ...
    def sync_from(self, shm_key: int) -> None: ...
    def sync_to(self, shm_key: int) -> None: ...
    def merge_from(self, shm_key: int) -> None: ...
    def read(self) -> None: ...
    def write(self) -> None: ...
