def get_dlf_src_path(package_name:str=None)->None:...

def insert_slipcover(**kwargs) -> None:...

def init_bitmap_python(**kwargs) -> None:...

def init_bitmap_c()->None:...

def init_bitmap(**kwargs) -> None: ...

def open_bitmap()->None: ...

def clear_bitmap_python() -> None: ...

def clear_bitmap_c() -> None:...

def clear_bitmap() -> None:...

def randomize_bitmap_python() -> None:...

def randomize_bitmap_c() -> None:...

def randomize_bitmap() -> None:...

def close_bitmap_python() -> None:...

def close_bitmap_c() -> None:...

def close_bitmap() -> None:...

def get_bb_cnt_python() -> int: ...

def get_bb_cnt_c() -> int:...

def get_bb_cnts() -> tuple[int, int]:...
