def get_bitmap_size() -> int: ...
def open_bitmap_py() -> None: ...
def open_bitmap_c() -> None: ...
def open_bitmap_java() -> None: ...
def clear_bitmap_py() -> None: ...
def clear_bitmap_c() -> None: ...
def clear_bitmap_java() -> None: ...
def close_bitmap_py() -> None: ...
def close_bitmap_c() -> None: ...
def close_bitmap_java() -> None: ...
def count_bits_py() -> int: ...
def count_bits_c() -> int: ...
def count_bits_java() -> int: ...
def on_hit_py(hit_id: int) -> None: ...
def on_hit_py_edge(edge_id: int) -> None: ...

# more flexible versions of the functions that take a key_name and key
def open_bitmap_x(key: int) -> None: ...
def clear_bitmap_x(key: int) -> None: ...
def close_bitmap_x(key: int) -> None: ...
def count_bits_x(key: int) -> int: ...
def copy_bitmap(ori: int, dst: int): ...
def merge_bitmap(ori: int, dst: int): ...
def count_aflpp_bytes(map_size: int, key: int) -> int: ...
